apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: "{app_uuid}"
spec:
  tag: "{tag}"
  serviceAccountName: "{service_account}"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: sb-drupal
    kind: ClusterStore
  order:
  - group:
    - id: shapeblock-buildpacks/php
    - id: shapeblock-buildpacks/composer
    - id: shapeblock-buildpacks/php-fpm
    - id: shapeblock-buildpacks/nginx
