apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: {{ app_uuid }}
spec:
  tag: "{tag}"
  serviceAccountName: "{service_account}"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: paketo-php
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ca-certificates
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/php-dist
    - id: paketo-buildpacks/php-composer
    - id: paketo-buildpacks/php-web
