apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: "{app_uuid}"
spec:
  tag: "{tag}"
  serviceAccountName: "{service_account}"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: sb-php
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ca-certificates
    - id: paketo-buildpacks/php-dist
    - id: paketo-buildpacks/composer
    - id: paketo-buildpacks/composer-install
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/php-fpm
    - id: paketo-buildpacks/php-nginx
    - id: paketo-buildpacks/php-start
    - id: shapeblock-buildpacks/apt
    - id: shapeblock-buildpacks/chmod
  - group:
    - id: paketo-buildpacks/ca-certificates
    - id: paketo-buildpacks/php-dist
    - id: paketo-buildpacks/composer
    - id: paketo-buildpacks/composer-install
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/php-fpm
    - id: paketo-buildpacks/php-nginx
    - id: paketo-buildpacks/php-start
    - id: paketo-buildpacks/nodejs
    - id: shapeblock-buildpacks/apt
    - id: shapeblock-buildpacks/chmod
  - group:
    - id: paketo-buildpacks/ca-certificates
    - id: paketo-buildpacks/php-dist
    - id: paketo-buildpacks/composer
    - id: paketo-buildpacks/composer-install
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/php-fpm
    - id: paketo-buildpacks/php-nginx
    - id: paketo-buildpacks/php-start
    - id: paketo-buildpacks/procfile
    - id: shapeblock-buildpacks/apt
    - id: shapeblock-buildpacks/chmod
  - group:
    - id: paketo-buildpacks/ca-certificates
    - id: paketo-buildpacks/php-dist
    - id: paketo-buildpacks/composer
    - id: paketo-buildpacks/composer-install
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/php-fpm
    - id: paketo-buildpacks/php-nginx
    - id: paketo-buildpacks/php-start
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
    - id: shapeblock-buildpacks/apt
    - id: shapeblock-buildpacks/chmod
