apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: "{name}"
spec:
  tag: "{tag}"
  serviceAccount: "{service_account}"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: paketo-node
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/nodejs
