apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: "{app_uuid}"
spec:
  tag: "{tag}"
  serviceAccountName: "{service_account}"
  stack:
    name: base
    kind: ClusterStack
  store:
    name: paketo-python
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/python
    - id: paketo-buildpacks/nodejs
    - id: shapeblock-buildpacks/chmod
  - group:
    - id: paketo-buildpacks/python
    - id: shapeblock-buildpacks/chmod
