apiVersion: v1
kind: ServiceAccount
metadata:
  name: shapeblock-admin
  namespace: shapeblock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shapeblock-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: shapeblock-admin
  namespace: shapeblock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-operator
  namespace: shapeblock
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: sb-operator
  template:
    metadata:
      labels:
        application: sb-operator
    spec:
      serviceAccountName: shapeblock-admin
      containers:
      - name: sb-operator
        image: shapeblock/sb-operator:20-dec-2024.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
        env:
          - name: SB_URL
            value: https://api.test1.lakshminp.xyz
          - name: CLUSTER_ID
            value: afbe-1234-5678-9012-3456
