FROM bitnami/kubectl:1.21

RUN wget -qO /opt/bitnami/kubectl/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /opt/bitnami/kubectl/bin/jq
RUN wget -qO /opt/bitnami/kubectl/bin/yj https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux && chmod +x /opt/bitnami/kubectl/bin/yj
RUN wget https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz -qO - | tar xz --strip-components=1 -C /opt/bitnami/kubectl/bin && chmod +x /opt/bitnami/kubectl/bin/helm && mkdir -p /opt/bitnami/helm/{config,cache}


RUN mkdir /opt/bitnami/project

COPY install-deps.sh /opt/bitnami/project/

ENV HELM_CONFIG_HOME=/opt/bitnami/helm/config
ENV HELM_CACHE_HOME=/opt/bitnami/helm/cache
ENV HELM_DRIVER=configmap

RUN helm repo add bitnami https://charts.bitnami.com/bitnami
RUN helm repo add twuni https://helm.twun.io
RUN helm repo add jetstack https://charts.jetstack.io
RUN helm repo add fluxcd https://charts.fluxcd.io
RUN helm repo add raphael https://raphaelmonrouzeau.github.io/charts/repository/

RUN helm repo update
WORKDIR /opt/bitnami/project
ENTRYPOINT []
CMD []
