apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: "{app_uuid}"
    shapeblock.com/deployment-uuid: "{deployment_uuid}"
spec:
  interval: 5m
  chart:
    spec:
      chart: "{chart_name}"
      version: "{chart_version}"
      sourceRef:
        kind: HelmRepository
        name: shapeblock
        namespace: flux
      interval: 1m
  install:
    disableWait: false
    disableWaitForJobs: false
