apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  annotations:
  name: "{name}"
  labels:
    shapeblock.com/app-uuid: "{app_uuid}"
spec:
  builder:
    kind: Builder
    name: "{builder_name}"
  build:
    env:
      - name: BP_PHP_WEB_DIR
        value: "web"
      - name: BP_PHP_VERSION
        value: "8.1"
  cache:
    volume:
      size: "2Gi"
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccountName: "{service_account}"
  source:
    git:
      revision: "{ref}"
      url: "{repo}"
  tag: "{tag}"