---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.dev.shapeblock.com
spec:
  group: dev.shapeblock.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Application is the Schema for the applications API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApplicationSpec defines the desired state of Application
            properties:
              buildConfig:
                properties:
                  clusterStack:
                    type: string
                  clusterStore:
                    type: string
                type: object
              chart:
                properties:
                  name:
                    type: string
                  repo:
                    type: string
                  values:
                    type: string
                  version:
                    type: string
                type: object
              git:
                properties:
                  ref:
                    type: string
                  repo:
                    type: string
                type: object
              serviceAccount:
                type: string
              tag:
                type: string
            type: object
          status:
            description: ApplicationStatus defines the observed state of Application
            properties:
              deployed:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: boolean
              image:
                type: string
              ref:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.dev.shapeblock.com
spec:
  group: dev.shapeblock.com
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              name:
                type: string
                description: The human readable name of the project.
              description:
                type: string
                description: What this project is about.
            type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sb-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sb-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sb-admin
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: sb-operator
  template:
    metadata:
      labels:
        application: sb-operator
    spec:
      serviceAccountName: sb-admin
      initContainers:
      - name: kubectl-container
        image: shapeblock/sb-operator-init:0.0.9
        command: ["bash","/opt/bitnami/project/install-deps.sh"]
        imagePullPolicy: Always
        env:
          - name: FLUX_HELM_OPERATOR_VERSION
            value: "1.4.0"
          - name: NGINX_INGRESS_VERSION
            value: "7.6.19"
          - name: CLUSTER_NAME
            value: "little-bird-ae3c"
          - name: CERT_MANAGER_VERSION
            value: "v1.5.2"
          - name: KPACK_VERSION
            value: "0.3.1"
          - name: NFS_VERSION
            value: "1.3.0"
          - name: CONTAINER_REGISTRY_VERSION
            value: "1.13.0"
          - name: NFS_SIZE
            value: "80Gi"
          - name: REGISTRY_SIZE
            value: "20Gi"
          - name: REGISTRY_URL
            value: "registry.little-bird-ae3c"
          - name: REGISTRY_PASSWORD
            value: "$2y$10$8Wjc9xlzoRnrlsK.RKULZuexrEwVliSKxI7dj92u.QQM7I4T6acVS"
          - name: REGISTRY_USERNAME
            value: "little-bird-ae3c-admin"
          - name: REGISTRY_CREDENTIALS
            value: "bGl0dGxlLWJpcmQtYWUzYy1hZG1pbjplQj9ydEs+akBpTGRfVSs1R3k5PTw8UDUyRzMK"
          - name: LETSENCRYPT_EMAIL
            value: lakshmi@lakshminp.com
      containers:
      - name: sb-operator
        image: shapeblock/sb-operator:0.0.9
