apiVersion: dev.shapeblock.com/v1alpha1
kind: Application
metadata:
  name: d9-01
  namespace: drupal-9
spec:
  # Add fields here
  tag: registry.little-bird-ae3c.shapeblock.cloud/drupal-9/d9-01
  git:
    repo: https://github.com/badri/d9-buildpack.git
    ref: 9122062360428660f565920dad54f02e47e16446
  chart:
    repo: https://shapeblock.github.io
    name: drupal
    version: "0.4.1"
    values: |
      autoscaling:
        enabled: false
      backup:
        enabled: false
      clusterDomain: little-bird-ae3c.shapeblock.cloud
      docroot: web
      elasticsearch:
        enabled: false
      imagePullSecrets:
      - name: registry-creds
      mailhog:
        enabled: false
      mariadb:
        db:
          name: drupal
          password: drupal
          user: drupal
        master:
          persistence:
            size: 2G
        volumePermissions:
          enabled: true
      memcached:
        enabled: false
      mounts:
        public-files:
          csiDriverName: null
          enabled: true
          mountPath: sites/default/files
          storage: 1G
          storageClassName: nfs
      nginx:
        basicauth:
          enabled: false
        image: bitnami/nginx:1.19
      php:
        image: registry.little-bird-ae3c.shapeblock.cloud/drupal-9/d9-01
      referenceData:
        enabled: false
      replicas: 1
      shell:
        enabled: false
      ssl:
        enabled: true
      varnish:
        enabled: false

